FROM php:8.3-fpm

RUN yes | pecl install xdebug && docker-php-ext-enable xdebug

RUN apt-get update && apt-get install -y \
libpq-dev \
&& docker-php-ext-install pdo pdo_pgsql
RUN rm -rf /var/lib/apt/lists/*

ENV COMPOSER_HOME /composer
ENV PATH /composer/vendor/bin:$PATH
ENV COMPOSER_ALLOW_SUPERUSER 1

COPY --from=composer /usr/bin/composer /usr/bin/composer
RUN apt-get update -y &&\
 apt-get install -y git zip unzip &&\
 rm -rf /var/lib/apt/lists/*

RUN mkdir -p "$COMPOSER_HOME/cache" \
&& mkdir -p "$COMPOSER_HOME/vendor" \
&& chown -R www-data:www-data $COMPOSER_HOME \
&& chown -R www-data:www-data /var/www

VOLUME /composer/cache